### ISSUE TITLE
Background and buttons of scrollbar in map-mode

### ISSUE THREAD

**Issue by vezixig** [kai-oswald/NightOwl-VS-Theme#10]
Only the currently visible part of the scrollbar has a dark background. The remaining part of the scrollbar has a light Background. The buttons at top and bottom of the scrollbar are having a light background also.

**Comment by maxdeviant** [comment]
I'm seeing this as well.

Here's a screenshot, for reference:

![image](https://user-images.githubusercontent.com/1486634/74249596-65457b80-4cb7-11ea-9420-7ad71451ef1b.png)

**Comment by kai-oswald** [comment]
Should be fixed in v0.1.6.

**Comment by maxdeviant** [comment]
@kai-oswald The fix works for me. Thanks for the quick resolution!
