### ISSUE TITLE
some text is unreadable

### ISSUE THREAD

**Issue by siddhant-nair** [kai-oswald/NightOwl-VS-Theme#16]
![image](https://user-images.githubusercontent.com/59318286/85919626-93081700-b88a-11ea-8a4a-8d04744ce6f4.png)

**Comment by siddhant-nair** [comment]
operators are unreadable too, only on a python project though. Its legible on my other C++ projects

**Comment by DrThrillhouse** [comment]
Created a pull request that fixes this problem:
![image](https://user-images.githubusercontent.com/14172590/88628530-b23fd180-d0e0-11ea-9d6e-a4e91841d5b3.png)
