### ISSUE TITLE
Misconfigured colors when debugging

### ISSUE THREAD

**Issue by verndals** [kai-oswald/NightOwl-VS-Theme#2]
I noticed some misconfigured colors when debugging. 

![debug_breakpoint](https://user-images.githubusercontent.com/1318073/63749680-3fb0eb00-c8ac-11e9-8825-16c3dd81e93f.png)
![debug_currentstep](https://user-images.githubusercontent.com/1318073/63749681-3fb0eb00-c8ac-11e9-98f9-d80e357d9481.png)
![debug_info](https://user-images.githubusercontent.com/1318073/63749682-3fb0eb00-c8ac-11e9-8c3b-ea4b0588106a.png)

**Comment by kai-oswald** [comment]
![image](https://user-images.githubusercontent.com/10707779/63751784-4d686f80-c8b0-11e9-812b-50a27b63a996.png)

Should be fixed with 11636d0 v0.1.2

Thanks :)
