### ISSUE TITLE
Base theme not found when opening solution in fresh VS Pro 2019 v 16.6.4

### ISSUE THREAD

**Issue by DrThrillhouse** [kai-oswald/NightOwl-VS-Theme#20]
I was hoping to style a couple of ReSharper elements and - if they turned out any good - create a PR for you folks to take a look. Unfortunately, when I try to open the theme in the Designer, I can't proceed until I've selected a base theme:
![image](https://user-images.githubusercontent.com/14172590/87945024-c11bf800-cad2-11ea-8feb-14cec0def57a.png)

Looking at the code, I can see the BaseGUID is 21aad376-802e-4d3f-9b99-3790e6ca7e9a, but that doesn't seem to conform to any theme I currently have installed.

If I'm missing something, I need to install something else or there's a workaround, perhaps I could update your ReadMe file.

**Comment by kai-oswald** [comment]
Hey,

I think the base theme for the designer is stored locally, therefore you can't see it.
Just select the "Night Owl" theme you've installed as extension 👍

**Comment by DrThrillhouse** [comment]
Thanks Kai. Interestingly, when I do that I end up with some unexpected colors. The image below shows my installed copy of NightOwl as the base theme and I'm on preview mode to show how it applies to the Visual Studio UI.

![image](https://user-images.githubusercontent.com/14172590/88055742-0b17e300-cb92-11ea-87b9-ef2df0e5be55.png)

What does it look like when you open the designer? Do you have a base theme selected?

**Comment by DrThrillhouse** [comment]
Ahhhh! I've just looked at the history of [NightOwl.vstheme](https://github.com/kai-oswald/NightOwl-VS-Theme/commits/master/NightOwl.vstheme) and I think I see your strategy is on each release you're moving GUID into BaseGUID and setting a new value for GUID, is that right? So in other words, your working version has a new GUID with the previous version as the BaseGUID.

There must be something else going on with my weird preview then, because I do have the latest version installed in my VS. I'll try to figure it out.

**Comment by DrThrillhouse** [comment]
Okay, seems like it might be a VS bug. When I **Apply** from the designer instead of just **Preview** it all works as expected. Sorry, first time working with VS themes :)

**Comment by kai-oswald** [comment]
You're fine :)
Yes, the Preview also bugs for me. 
I also noticed some tokens not showing or Visual Studio crashing when editing colors through the theme designer. 
If you open the `.vstheme` file in an editor like Visual Studio Code, you can just edit the XML directly.
However, I think the theme designer is still handy to search for specific color tokens.
