### ISSUE TITLE
C++ not supported

### ISSUE THREAD

**Issue by CrHasher** [kai-oswald/NightOwl-VS-Theme#27]
The theme has minimal support for C++, most of the colors are totally different from Visual Studio Code.

Can this be fixed? I really like this theme but I did not manage to fix the colors myself, did it only by messing with Fonts and Colors in Visual Studio options and ended reverting the changes in the end.

**Comment by CrHasher** [comment]
Pull request added to fix issue: https://github.com/kai-oswald/NightOwl-VS-Theme/pull/28

**Comment by CrHasher** [comment]
@kai-oswald Please add the c++ demo files from original VSCode theme when you have the time

**Comment by kai-oswald** [comment]
Hey @CrHasher!

Thanks a lot for the pull requests. Will be shipped with v0.2.0 in a couple minutes :)

**Comment by CrHasher** [comment]
Night Owl is an awesome theme, will most probably use it for a while.
Thanks for making a theme for VS.
