### ISSUE TITLE
Solution Explorer Track active Item background-color

### ISSUE THREAD

**Issue by gds03** [kai-oswald/NightOwl-VS-Theme#29]
HI.

I have "Track active Item" enabled and I can't see it with any background color being applied.
I tried in another machine and it doesn't apply also.

![Capture](https://user-images.githubusercontent.com/1148651/101365770-18611000-389c-11eb-9329-56552f86014b.PNG)

**Comment by CrHasher** [comment]
Fixed in pull request: https://github.com/kai-oswald/NightOwl-VS-Theme/pull/33
