### ISSUE TITLE
Update for Visual Studio 2022

### ISSUE THREAD

**Issue by TanvirArjel** [kai-oswald/NightOwl-VS-Theme#34]
This theme looks awesome but unfortunately no support for **Visual Studio 2022** yet. Please update the theme for Visual Stduio 2022.

Thanks in advance.

**Comment by Abracadabras** [comment]
I need help with this

**Comment by kai-oswald** [comment]
Somebody already built the theme at https://marketplace.visualstudio.com/items?itemName=God0nlyKnows.NightOwl&ssr=false#overview
