### ISSUE TITLE
Does anyone else feel that comments are a bit hard to read?

### ISSUE THREAD

**Issue by verndals** [kai-oswald/NightOwl-VS-Theme#4]
![swag](https://user-images.githubusercontent.com/1318073/64114177-a3478680-cd8c-11e9-840e-4eed55528d91.png)

**Comment by kai-oswald** [comment]
I agree that it can be hard to read sometimes, but this is the same color as the original vscode theme.

https://github.com/sdras/night-owl-vscode-theme/blob/3798218b24f2d78c4f05cbb020baf85a268c3241/themes/Night%20Owl-color-theme.json#L254

**Comment by maxdeviant** [comment]
As a counter-point, I think that the comments are perfectly legible, as seen below.

![image](https://user-images.githubusercontent.com/1486634/66048573-c6826480-e4f7-11e9-8647-925eb42f816e.png)

Although it does seem like there is more contrast in my screenshot than in @verndals'. Not sure why that would be...

Either way, this is a Night Owl port so I don't think we should be straying from the colors from the original theme.
