### ISSUE TITLE
The separation of windows are missing some sort of indicator (border?)

### ISSUE THREAD

**Issue by verndals** [kai-oswald/NightOwl-VS-Theme#5]
![windows](https://user-images.githubusercontent.com/1318073/64114958-b52a2900-cd8e-11e9-8a62-b89917e6b2ce.png)

**Comment by kai-oswald** [comment]
The original theme doesn't really use borders too and I honestly think it's fine once you get used to the theme.

https://github.com/sdras/night-owl-vscode-theme#separate-the-editor-from-the-sidebar

What we could do is to offer a "High Contrast" version with a clear separation of windows.

**Comment by DrThrillhouse** [comment]
If you're interested in forking this project and doing it yourself, the bit of code you want to change is around line 4463 of [NightOwl.vstheme](https://github.com/kai-oswald/NightOwl-VS-Theme/blob/master/NightOwl.vstheme)
```
      <Color Name="ToolWindowBorder">
        <Background Type="CT_RAW" Source="FF011627" />
      </Color>
```
Something like FF1D3B53 might make a decently unobtrusive replacement color if you wanted to stick with the NightOwl color scheme. That would result in something like this:

![image](https://user-images.githubusercontent.com/14172590/88798594-b39ff580-d1d7-11ea-987e-db6977a04471.png)
